cluster: 
  name: bigdata-dev-cluster
  mysql:
    ip: 192.168.10.70
    port: 3306 
    username: root
    password: pwd@123

  postgres:
    ip: 192.168.10.68
    port: 5432
    username: postgres
    password: pwd@123
    datasourceinfo:
      schema: cluster