apiVersion: v1
kind: Service
metadata:
  name: service-monitor-exporter-service
  labels:
    app: service-monitor-exporter
spec:
  selector:
    app: service-monitor-exporter
  ports:
    - name: http
      protocol: TCP
      port: 38080
      targetPort: 38080
      nodePort: 18080
  type: NodePort