# testclu:
#   hostips: 
#     - 192.168.3.1
#     - 192.168.3.2
#     - 192.168.3.3
#   port: 1521
#   dbuser: system
#   passwd: 123456
#   service_name: testdb


masterhttp:
  ips: 
    - 192.168.10.220
    - 192.168.10.221
    - 192.168.10.222
  port: 8080
  path: /metrics/prometheus
  
applicationhttp:
  ips:
    - 192.168.10.220
    - 192.168.10.221
    - 192.168.10.222
  ports:
    - 4040
    - 4041
    - 4042
  mainpath: /metrics/prometheus
  executorpath: /metrics/executors/prometheus