// This file was generated from JSON Schema using quicktype, do not modify it directly.
// To parse and unparse this JSON data, add this code to your project and do:
//
//    regionserverServer, err := UnmarshalRegionserverServer(bytes)
//    bytes, err = regionserverServer.Marshal()

package hbase

import "encoding/json"

func UnmarshalRegionserverServer(data []byte) (RegionserverServer, error) {
	var r RegionserverServer
	err := json.Unmarshal(data, &r)
	return r, err
}

func (r *RegionserverServer) Marshal() ([]byte, error) {
	return json.Marshal(r)
}

type RegionserverServer struct {
	Beans []ServerBean `json:"beans,omitempty"`
}

type ServerBean struct {
	Name                                          *string  `json:"name,omitempty"`
	ModelerType                                   *string  `json:"modelerType,omitempty"`
	TagZookeeperQuorum                            *string  `json:"tag.zookeeperQuorum,omitempty"`
	TagServerName                                 *string  `json:"tag.serverName,omitempty"`
	TagClusterID                                  *string  `json:"tag.clusterId,omitempty"`
	TagContext                                    *string  `json:"tag.Context,omitempty"`
	TagHostname                                   *string  `json:"tag.Hostname,omitempty"`
	RegionCount                                   *int64   `json:"regionCount,omitempty"`
	StoreCount                                    *int64   `json:"storeCount,omitempty"`
	HlogFileCount                                 *int64   `json:"hlogFileCount,omitempty"`
	HlogFileSize                                  *int64   `json:"hlogFileSize,omitempty"`
	StoreFileCount                                *int64   `json:"storeFileCount,omitempty"`
	MemStoreSize                                  *int64   `json:"memStoreSize,omitempty"`
	StoreFileSize                                 *int64   `json:"storeFileSize,omitempty"`
	MaxStoreFileAge                               *int64   `json:"maxStoreFileAge,omitempty"`
	MinStoreFileAge                               *int64   `json:"minStoreFileAge,omitempty"`
	AvgStoreFileAge                               *int64   `json:"avgStoreFileAge,omitempty"`
	NumReferenceFiles                             *int64   `json:"numReferenceFiles,omitempty"`
	RegionServerStartTime                         *int64   `json:"regionServerStartTime,omitempty"`
	AverageRegionSize                             *int64   `json:"averageRegionSize,omitempty"`
	StoreFileIndexSize                            *int64   `json:"storeFileIndexSize,omitempty"`
	StaticIndexSize                               *int64   `json:"staticIndexSize,omitempty"`
	StaticBloomSize                               *int64   `json:"staticBloomSize,omitempty"`
	MutationsWithoutWALCount                      *int64   `json:"mutationsWithoutWALCount,omitempty"`
	MutationsWithoutWALSize                       *int64   `json:"mutationsWithoutWALSize,omitempty"`
	PercentFilesLocal                             *int64   `json:"percentFilesLocal,omitempty"`
	PercentFilesLocalSecondaryRegions             *int64   `json:"percentFilesLocalSecondaryRegions,omitempty"`
	TotalBytesRead                                *int64   `json:"totalBytesRead,omitempty"`
	LocalBytesRead                                *int64   `json:"localBytesRead,omitempty"`
	ShortCircuitBytesRead                         *int64   `json:"shortCircuitBytesRead,omitempty"`
	ZeroCopyBytesRead                             *int64   `json:"zeroCopyBytesRead,omitempty"`
	SplitQueueLength                              *int64   `json:"splitQueueLength,omitempty"`
	CompactionQueueLength                         *int64   `json:"compactionQueueLength,omitempty"`
	SmallCompactionQueueLength                    *int64   `json:"smallCompactionQueueLength,omitempty"`
	LargeCompactionQueueLength                    *int64   `json:"largeCompactionQueueLength,omitempty"`
	FlushQueueLength                              *int64   `json:"flushQueueLength,omitempty"`
	BlockCacheFreeSize                            *int64   `json:"blockCacheFreeSize,omitempty"`
	BlockCacheCount                               *int64   `json:"blockCacheCount,omitempty"`
	BlockCacheSize                                *int64   `json:"blockCacheSize,omitempty"`
	BlockCacheCountHitPercent                     *float64 `json:"blockCacheCountHitPercent,omitempty"`
	BlockCacheExpressHitPercent                   *float64 `json:"blockCacheExpressHitPercent,omitempty"`
	L1CacheHitCount                               *int64   `json:"l1CacheHitCount,omitempty"`
	L1CacheMissCount                              *int64   `json:"l1CacheMissCount,omitempty"`
	L1CacheHitRatio                               *int64   `json:"l1CacheHitRatio,omitempty"`
	L1CacheMissRatio                              *int64   `json:"l1CacheMissRatio,omitempty"`
	L2CacheHitCount                               *int64   `json:"l2CacheHitCount,omitempty"`
	L2CacheMissCount                              *int64   `json:"l2CacheMissCount,omitempty"`
	L2CacheHitRatio                               *int64   `json:"l2CacheHitRatio,omitempty"`
	L2CacheMissRatio                              *int64   `json:"l2CacheMissRatio,omitempty"`
	MobFileCacheCount                             *int64   `json:"mobFileCacheCount,omitempty"`
	MobFileCacheHitPercent                        *int64   `json:"mobFileCacheHitPercent,omitempty"`
	ReadRequestRatePerSecond                      *int64   `json:"readRequestRatePerSecond,omitempty"`
	WriteRequestRatePerSecond                     *int64   `json:"writeRequestRatePerSecond,omitempty"`
	ByteBuffAllocatorHeapAllocationBytes          *int64   `json:"ByteBuffAllocatorHeapAllocationBytes,omitempty"`
	ByteBuffAllocatorPoolAllocationBytes          *int64   `json:"ByteBuffAllocatorPoolAllocationBytes,omitempty"`
	ByteBuffAllocatorHeapAllocationRatio          *int64   `json:"ByteBuffAllocatorHeapAllocationRatio,omitempty"`
	ByteBuffAllocatorTotalBufferCount             *int64   `json:"ByteBuffAllocatorTotalBufferCount,omitempty"`
	ByteBuffAllocatorUsedBufferCount              *int64   `json:"ByteBuffAllocatorUsedBufferCount,omitempty"`
	TotalRequestCount                             *int64   `json:"totalRequestCount,omitempty"`
	TotalRowActionRequestCount                    *int64   `json:"totalRowActionRequestCount,omitempty"`
	ReadRequestCount                              *int64   `json:"readRequestCount,omitempty"`
	FilteredReadRequestCount                      *int64   `json:"filteredReadRequestCount,omitempty"`
	WriteRequestCount                             *int64   `json:"writeRequestCount,omitempty"`
	RPCGetRequestCount                            *int64   `json:"rpcGetRequestCount,omitempty"`
	RPCScanRequestCount                           *int64   `json:"rpcScanRequestCount,omitempty"`
	RPCMultiRequestCount                          *int64   `json:"rpcMultiRequestCount,omitempty"`
	RPCMutateRequestCount                         *int64   `json:"rpcMutateRequestCount,omitempty"`
	CheckMutateFailedCount                        *int64   `json:"checkMutateFailedCount,omitempty"`
	CheckMutatePassedCount                        *int64   `json:"checkMutatePassedCount,omitempty"`
	BlockCacheHitCount                            *int64   `json:"blockCacheHitCount,omitempty"`
	BlockCacheHitCountPrimary                     *int64   `json:"blockCacheHitCountPrimary,omitempty"`
	BlockCacheMissCount                           *int64   `json:"blockCacheMissCount,omitempty"`
	BlockCacheMissCountPrimary                    *int64   `json:"blockCacheMissCountPrimary,omitempty"`
	BlockCacheEvictionCount                       *int64   `json:"blockCacheEvictionCount,omitempty"`
	BlockCacheEvictionCountPrimary                *int64   `json:"blockCacheEvictionCountPrimary,omitempty"`
	BlockCacheFailedInsertionCount                *int64   `json:"blockCacheFailedInsertionCount,omitempty"`
	BlockCacheDataMissCount                       *int64   `json:"blockCacheDataMissCount,omitempty"`
	BlockCacheLeafIndexMissCount                  *int64   `json:"blockCacheLeafIndexMissCount,omitempty"`
	BlockCacheBloomChunkMissCount                 *int64   `json:"blockCacheBloomChunkMissCount,omitempty"`
	BlockCacheMetaMissCount                       *int64   `json:"blockCacheMetaMissCount,omitempty"`
	BlockCacheRootIndexMissCount                  *int64   `json:"blockCacheRootIndexMissCount,omitempty"`
	BlockCacheIntermediateIndexMissCount          *int64   `json:"blockCacheIntermediateIndexMissCount,omitempty"`
	BlockCacheFileInfoMissCount                   *int64   `json:"blockCacheFileInfoMissCount,omitempty"`
	BlockCacheGeneralBloomMetaMissCount           *int64   `json:"blockCacheGeneralBloomMetaMissCount,omitempty"`
	BlockCacheDeleteFamilyBloomMissCount          *int64   `json:"blockCacheDeleteFamilyBloomMissCount,omitempty"`
	BlockCacheTrailerMissCount                    *int64   `json:"blockCacheTrailerMissCount,omitempty"`
	BlockCacheDataHitCount                        *int64   `json:"blockCacheDataHitCount,omitempty"`
	BlockCacheLeafIndexHitCount                   *int64   `json:"blockCacheLeafIndexHitCount,omitempty"`
	BlockCacheBloomChunkHitCount                  *int64   `json:"blockCacheBloomChunkHitCount,omitempty"`
	BlockCacheMetaHitCount                        *int64   `json:"blockCacheMetaHitCount,omitempty"`
	BlockCacheRootIndexHitCount                   *int64   `json:"blockCacheRootIndexHitCount,omitempty"`
	BlockCacheIntermediateIndexHitCount           *int64   `json:"blockCacheIntermediateIndexHitCount,omitempty"`
	BlockCacheFileInfoHitCount                    *int64   `json:"blockCacheFileInfoHitCount,omitempty"`
	BlockCacheGeneralBloomMetaHitCount            *int64   `json:"blockCacheGeneralBloomMetaHitCount,omitempty"`
	BlockCacheDeleteFamilyBloomHitCount           *int64   `json:"blockCacheDeleteFamilyBloomHitCount,omitempty"`
	BlockCacheTrailerHitCount                     *int64   `json:"blockCacheTrailerHitCount,omitempty"`
	UpdatesBlockedTime                            *int64   `json:"updatesBlockedTime,omitempty"`
	FlushedCellsCount                             *int64   `json:"flushedCellsCount,omitempty"`
	CompactedCellsCount                           *int64   `json:"compactedCellsCount,omitempty"`
	MajorCompactedCellsCount                      *int64   `json:"majorCompactedCellsCount,omitempty"`
	FlushedCellsSize                              *int64   `json:"flushedCellsSize,omitempty"`
	CompactedCellsSize                            *int64   `json:"compactedCellsSize,omitempty"`
	MajorCompactedCellsSize                       *int64   `json:"majorCompactedCellsSize,omitempty"`
	CellsCountCompactedFromMob                    *int64   `json:"cellsCountCompactedFromMob,omitempty"`
	CellsCountCompactedToMob                      *int64   `json:"cellsCountCompactedToMob,omitempty"`
	CellsSizeCompactedFromMob                     *int64   `json:"cellsSizeCompactedFromMob,omitempty"`
	CellsSizeCompactedToMob                       *int64   `json:"cellsSizeCompactedToMob,omitempty"`
	MobFlushCount                                 *int64   `json:"mobFlushCount,omitempty"`
	MobFlushedCellsCount                          *int64   `json:"mobFlushedCellsCount,omitempty"`
	MobFlushedCellsSize                           *int64   `json:"mobFlushedCellsSize,omitempty"`
	MobScanCellsCount                             *int64   `json:"mobScanCellsCount,omitempty"`
	MobScanCellsSize                              *int64   `json:"mobScanCellsSize,omitempty"`
	MobFileCacheAccessCount                       *int64   `json:"mobFileCacheAccessCount,omitempty"`
	MobFileCacheMissCount                         *int64   `json:"mobFileCacheMissCount,omitempty"`
	MobFileCacheEvictedCount                      *int64   `json:"mobFileCacheEvictedCount,omitempty"`
	HedgedReads                                   *int64   `json:"hedgedReads,omitempty"`
	HedgedReadWINS                                *int64   `json:"hedgedReadWins,omitempty"`
	BlockedRequestCount                           *int64   `json:"blockedRequestCount,omitempty"`
	MajorCompactionTimeNumOps                     *int64   `json:"MajorCompactionTime_num_ops,omitempty"`
	MajorCompactionTimeMin                        *int64   `json:"MajorCompactionTime_min,omitempty"`
	MajorCompactionTimeMax                        *int64   `json:"MajorCompactionTime_max,omitempty"`
	MajorCompactionTimeMean                       *int64   `json:"MajorCompactionTime_mean,omitempty"`
	MajorCompactionTime25ThPercentile             *int64   `json:"MajorCompactionTime_25th_percentile,omitempty"`
	MajorCompactionTimeMedian                     *int64   `json:"MajorCompactionTime_median,omitempty"`
	MajorCompactionTime75ThPercentile             *int64   `json:"MajorCompactionTime_75th_percentile,omitempty"`
	MajorCompactionTime90ThPercentile             *int64   `json:"MajorCompactionTime_90th_percentile,omitempty"`
	MajorCompactionTime95ThPercentile             *int64   `json:"MajorCompactionTime_95th_percentile,omitempty"`
	MajorCompactionTime98ThPercentile             *int64   `json:"MajorCompactionTime_98th_percentile,omitempty"`
	MajorCompactionTime99ThPercentile             *int64   `json:"MajorCompactionTime_99th_percentile,omitempty"`
	MajorCompactionTime999ThPercentile            *int64   `json:"MajorCompactionTime_99.9th_percentile,omitempty"`
	PauseTimeWithGcNumOps                         *int64   `json:"PauseTimeWithGc_num_ops,omitempty"`
	PauseTimeWithGcMin                            *int64   `json:"PauseTimeWithGc_min,omitempty"`
	PauseTimeWithGcMax                            *int64   `json:"PauseTimeWithGc_max,omitempty"`
	PauseTimeWithGcMean                           *int64   `json:"PauseTimeWithGc_mean,omitempty"`
	PauseTimeWithGc25ThPercentile                 *int64   `json:"PauseTimeWithGc_25th_percentile,omitempty"`
	PauseTimeWithGcMedian                         *int64   `json:"PauseTimeWithGc_median,omitempty"`
	PauseTimeWithGc75ThPercentile                 *int64   `json:"PauseTimeWithGc_75th_percentile,omitempty"`
	PauseTimeWithGc90ThPercentile                 *int64   `json:"PauseTimeWithGc_90th_percentile,omitempty"`
	PauseTimeWithGc95ThPercentile                 *int64   `json:"PauseTimeWithGc_95th_percentile,omitempty"`
	PauseTimeWithGc98ThPercentile                 *int64   `json:"PauseTimeWithGc_98th_percentile,omitempty"`
	PauseTimeWithGc99ThPercentile                 *int64   `json:"PauseTimeWithGc_99th_percentile,omitempty"`
	PauseTimeWithGc999ThPercentile                *int64   `json:"PauseTimeWithGc_99.9th_percentile,omitempty"`
	CompactedOutputBytes                          *int64   `json:"compactedOutputBytes,omitempty"`
	PauseWarnThresholdExceeded                    *int64   `json:"pauseWarnThresholdExceeded,omitempty"`
	ScanTimeNumOps                                *int64   `json:"ScanTime_num_ops,omitempty"`
	ScanTimeMin                                   *int64   `json:"ScanTime_min,omitempty"`
	ScanTimeMax                                   *int64   `json:"ScanTime_max,omitempty"`
	ScanTimeMean                                  *int64   `json:"ScanTime_mean,omitempty"`
	ScanTime25ThPercentile                        *int64   `json:"ScanTime_25th_percentile,omitempty"`
	ScanTimeMedian                                *int64   `json:"ScanTime_median,omitempty"`
	ScanTime75ThPercentile                        *int64   `json:"ScanTime_75th_percentile,omitempty"`
	ScanTime90ThPercentile                        *int64   `json:"ScanTime_90th_percentile,omitempty"`
	ScanTime95ThPercentile                        *int64   `json:"ScanTime_95th_percentile,omitempty"`
	ScanTime98ThPercentile                        *int64   `json:"ScanTime_98th_percentile,omitempty"`
	ScanTime99ThPercentile                        *int64   `json:"ScanTime_99th_percentile,omitempty"`
	ScanTime999ThPercentile                       *int64   `json:"ScanTime_99.9th_percentile,omitempty"`
	IncrementNumOps                               *int64   `json:"Increment_num_ops,omitempty"`
	IncrementMin                                  *int64   `json:"Increment_min,omitempty"`
	IncrementMax                                  *int64   `json:"Increment_max,omitempty"`
	IncrementMean                                 *int64   `json:"Increment_mean,omitempty"`
	Increment25ThPercentile                       *int64   `json:"Increment_25th_percentile,omitempty"`
	IncrementMedian                               *int64   `json:"Increment_median,omitempty"`
	Increment75ThPercentile                       *int64   `json:"Increment_75th_percentile,omitempty"`
	Increment90ThPercentile                       *int64   `json:"Increment_90th_percentile,omitempty"`
	Increment95ThPercentile                       *int64   `json:"Increment_95th_percentile,omitempty"`
	Increment98ThPercentile                       *int64   `json:"Increment_98th_percentile,omitempty"`
	Increment99ThPercentile                       *int64   `json:"Increment_99th_percentile,omitempty"`
	Increment999ThPercentile                      *int64   `json:"Increment_99.9th_percentile,omitempty"`
	DeleteNumOps                                  *int64   `json:"Delete_num_ops,omitempty"`
	DeleteMin                                     *int64   `json:"Delete_min,omitempty"`
	DeleteMax                                     *int64   `json:"Delete_max,omitempty"`
	DeleteMean                                    *int64   `json:"Delete_mean,omitempty"`
	Delete25ThPercentile                          *int64   `json:"Delete_25th_percentile,omitempty"`
	DeleteMedian                                  *int64   `json:"Delete_median,omitempty"`
	Delete75ThPercentile                          *int64   `json:"Delete_75th_percentile,omitempty"`
	Delete90ThPercentile                          *int64   `json:"Delete_90th_percentile,omitempty"`
	Delete95ThPercentile                          *int64   `json:"Delete_95th_percentile,omitempty"`
	Delete98ThPercentile                          *int64   `json:"Delete_98th_percentile,omitempty"`
	Delete99ThPercentile                          *int64   `json:"Delete_99th_percentile,omitempty"`
	Delete999ThPercentile                         *int64   `json:"Delete_99.9th_percentile,omitempty"`
	PutNumOps                                     *int64   `json:"Put_num_ops,omitempty"`
	PutMin                                        *int64   `json:"Put_min,omitempty"`
	PutMax                                        *int64   `json:"Put_max,omitempty"`
	PutMean                                       *int64   `json:"Put_mean,omitempty"`
	Put25ThPercentile                             *int64   `json:"Put_25th_percentile,omitempty"`
	PutMedian                                     *int64   `json:"Put_median,omitempty"`
	Put75ThPercentile                             *int64   `json:"Put_75th_percentile,omitempty"`
	Put90ThPercentile                             *int64   `json:"Put_90th_percentile,omitempty"`
	Put95ThPercentile                             *int64   `json:"Put_95th_percentile,omitempty"`
	Put98ThPercentile                             *int64   `json:"Put_98th_percentile,omitempty"`
	Put99ThPercentile                             *int64   `json:"Put_99th_percentile,omitempty"`
	Put999ThPercentile                            *int64   `json:"Put_99.9th_percentile,omitempty"`
	DeleteBatchNumOps                             *int64   `json:"DeleteBatch_num_ops,omitempty"`
	DeleteBatchMin                                *int64   `json:"DeleteBatch_min,omitempty"`
	DeleteBatchMax                                *int64   `json:"DeleteBatch_max,omitempty"`
	DeleteBatchMean                               *int64   `json:"DeleteBatch_mean,omitempty"`
	DeleteBatch25ThPercentile                     *int64   `json:"DeleteBatch_25th_percentile,omitempty"`
	DeleteBatchMedian                             *int64   `json:"DeleteBatch_median,omitempty"`
	DeleteBatch75ThPercentile                     *int64   `json:"DeleteBatch_75th_percentile,omitempty"`
	DeleteBatch90ThPercentile                     *int64   `json:"DeleteBatch_90th_percentile,omitempty"`
	DeleteBatch95ThPercentile                     *int64   `json:"DeleteBatch_95th_percentile,omitempty"`
	DeleteBatch98ThPercentile                     *int64   `json:"DeleteBatch_98th_percentile,omitempty"`
	DeleteBatch99ThPercentile                     *int64   `json:"DeleteBatch_99th_percentile,omitempty"`
	DeleteBatch999ThPercentile                    *int64   `json:"DeleteBatch_99.9th_percentile,omitempty"`
	SplitRequestCount                             *int64   `json:"splitRequestCount,omitempty"`
	FlushMemstoreSizeNumOps                       *int64   `json:"FlushMemstoreSize_num_ops,omitempty"`
	FlushMemstoreSizeMin                          *int64   `json:"FlushMemstoreSize_min,omitempty"`
	FlushMemstoreSizeMax                          *int64   `json:"FlushMemstoreSize_max,omitempty"`
	FlushMemstoreSizeMean                         *int64   `json:"FlushMemstoreSize_mean,omitempty"`
	FlushMemstoreSize25ThPercentile               *int64   `json:"FlushMemstoreSize_25th_percentile,omitempty"`
	FlushMemstoreSizeMedian                       *int64   `json:"FlushMemstoreSize_median,omitempty"`
	FlushMemstoreSize75ThPercentile               *int64   `json:"FlushMemstoreSize_75th_percentile,omitempty"`
	FlushMemstoreSize90ThPercentile               *int64   `json:"FlushMemstoreSize_90th_percentile,omitempty"`
	FlushMemstoreSize95ThPercentile               *int64   `json:"FlushMemstoreSize_95th_percentile,omitempty"`
	FlushMemstoreSize98ThPercentile               *int64   `json:"FlushMemstoreSize_98th_percentile,omitempty"`
	FlushMemstoreSize99ThPercentile               *int64   `json:"FlushMemstoreSize_99th_percentile,omitempty"`
	FlushMemstoreSize999ThPercentile              *int64   `json:"FlushMemstoreSize_99.9th_percentile,omitempty"`
	CompactionInputFileCountNumOps                *int64   `json:"CompactionInputFileCount_num_ops,omitempty"`
	CompactionInputFileCountMin                   *int64   `json:"CompactionInputFileCount_min,omitempty"`
	CompactionInputFileCountMax                   *int64   `json:"CompactionInputFileCount_max,omitempty"`
	CompactionInputFileCountMean                  *int64   `json:"CompactionInputFileCount_mean,omitempty"`
	CompactionInputFileCount25ThPercentile        *int64   `json:"CompactionInputFileCount_25th_percentile,omitempty"`
	CompactionInputFileCountMedian                *int64   `json:"CompactionInputFileCount_median,omitempty"`
	CompactionInputFileCount75ThPercentile        *int64   `json:"CompactionInputFileCount_75th_percentile,omitempty"`
	CompactionInputFileCount90ThPercentile        *int64   `json:"CompactionInputFileCount_90th_percentile,omitempty"`
	CompactionInputFileCount95ThPercentile        *int64   `json:"CompactionInputFileCount_95th_percentile,omitempty"`
	CompactionInputFileCount98ThPercentile        *int64   `json:"CompactionInputFileCount_98th_percentile,omitempty"`
	CompactionInputFileCount99ThPercentile        *int64   `json:"CompactionInputFileCount_99th_percentile,omitempty"`
	CompactionInputFileCount999ThPercentile       *int64   `json:"CompactionInputFileCount_99.9th_percentile,omitempty"`
	PutBatchNumOps                                *int64   `json:"PutBatch_num_ops,omitempty"`
	PutBatchMin                                   *int64   `json:"PutBatch_min,omitempty"`
	PutBatchMax                                   *int64   `json:"PutBatch_max,omitempty"`
	PutBatchMean                                  *int64   `json:"PutBatch_mean,omitempty"`
	PutBatch25ThPercentile                        *int64   `json:"PutBatch_25th_percentile,omitempty"`
	PutBatchMedian                                *int64   `json:"PutBatch_median,omitempty"`
	PutBatch75ThPercentile                        *int64   `json:"PutBatch_75th_percentile,omitempty"`
	PutBatch90ThPercentile                        *int64   `json:"PutBatch_90th_percentile,omitempty"`
	PutBatch95ThPercentile                        *int64   `json:"PutBatch_95th_percentile,omitempty"`
	PutBatch98ThPercentile                        *int64   `json:"PutBatch_98th_percentile,omitempty"`
	PutBatch99ThPercentile                        *int64   `json:"PutBatch_99th_percentile,omitempty"`
	PutBatch999ThPercentile                       *int64   `json:"PutBatch_99.9th_percentile,omitempty"`
	CompactionTimeNumOps                          *int64   `json:"CompactionTime_num_ops,omitempty"`
	CompactionTimeMin                             *int64   `json:"CompactionTime_min,omitempty"`
	CompactionTimeMax                             *int64   `json:"CompactionTime_max,omitempty"`
	CompactionTimeMean                            *int64   `json:"CompactionTime_mean,omitempty"`
	CompactionTime25ThPercentile                  *int64   `json:"CompactionTime_25th_percentile,omitempty"`
	CompactionTimeMedian                          *int64   `json:"CompactionTime_median,omitempty"`
	CompactionTime75ThPercentile                  *int64   `json:"CompactionTime_75th_percentile,omitempty"`
	CompactionTime90ThPercentile                  *int64   `json:"CompactionTime_90th_percentile,omitempty"`
	CompactionTime95ThPercentile                  *int64   `json:"CompactionTime_95th_percentile,omitempty"`
	CompactionTime98ThPercentile                  *int64   `json:"CompactionTime_98th_percentile,omitempty"`
	CompactionTime99ThPercentile                  *int64   `json:"CompactionTime_99th_percentile,omitempty"`
	CompactionTime999ThPercentile                 *int64   `json:"CompactionTime_99.9th_percentile,omitempty"`
	GetNumOps                                     *int64   `json:"Get_num_ops,omitempty"`
	GetMin                                        *int64   `json:"Get_min,omitempty"`
	GetMax                                        *int64   `json:"Get_max,omitempty"`
	GetMean                                       *int64   `json:"Get_mean,omitempty"`
	Get25ThPercentile                             *int64   `json:"Get_25th_percentile,omitempty"`
	GetMedian                                     *int64   `json:"Get_median,omitempty"`
	Get75ThPercentile                             *int64   `json:"Get_75th_percentile,omitempty"`
	Get90ThPercentile                             *int64   `json:"Get_90th_percentile,omitempty"`
	Get95ThPercentile                             *int64   `json:"Get_95th_percentile,omitempty"`
	Get98ThPercentile                             *int64   `json:"Get_98th_percentile,omitempty"`
	Get99ThPercentile                             *int64   `json:"Get_99th_percentile,omitempty"`
	Get999ThPercentile                            *int64   `json:"Get_99.9th_percentile,omitempty"`
	MajorCompactionInputFileCountNumOps           *int64   `json:"MajorCompactionInputFileCount_num_ops,omitempty"`
	MajorCompactionInputFileCountMin              *int64   `json:"MajorCompactionInputFileCount_min,omitempty"`
	MajorCompactionInputFileCountMax              *int64   `json:"MajorCompactionInputFileCount_max,omitempty"`
	MajorCompactionInputFileCountMean             *int64   `json:"MajorCompactionInputFileCount_mean,omitempty"`
	MajorCompactionInputFileCount25ThPercentile   *int64   `json:"MajorCompactionInputFileCount_25th_percentile,omitempty"`
	MajorCompactionInputFileCountMedian           *int64   `json:"MajorCompactionInputFileCount_median,omitempty"`
	MajorCompactionInputFileCount75ThPercentile   *int64   `json:"MajorCompactionInputFileCount_75th_percentile,omitempty"`
	MajorCompactionInputFileCount90ThPercentile   *int64   `json:"MajorCompactionInputFileCount_90th_percentile,omitempty"`
	MajorCompactionInputFileCount95ThPercentile   *int64   `json:"MajorCompactionInputFileCount_95th_percentile,omitempty"`
	MajorCompactionInputFileCount98ThPercentile   *int64   `json:"MajorCompactionInputFileCount_98th_percentile,omitempty"`
	MajorCompactionInputFileCount99ThPercentile   *int64   `json:"MajorCompactionInputFileCount_99th_percentile,omitempty"`
	MajorCompactionInputFileCount999ThPercentile  *int64   `json:"MajorCompactionInputFileCount_99.9th_percentile,omitempty"`
	CheckAndPutNumOps                             *int64   `json:"CheckAndPut_num_ops,omitempty"`
	CheckAndPutMin                                *int64   `json:"CheckAndPut_min,omitempty"`
	CheckAndPutMax                                *int64   `json:"CheckAndPut_max,omitempty"`
	CheckAndPutMean                               *int64   `json:"CheckAndPut_mean,omitempty"`
	CheckAndPut25ThPercentile                     *int64   `json:"CheckAndPut_25th_percentile,omitempty"`
	CheckAndPutMedian                             *int64   `json:"CheckAndPut_median,omitempty"`
	CheckAndPut75ThPercentile                     *int64   `json:"CheckAndPut_75th_percentile,omitempty"`
	CheckAndPut90ThPercentile                     *int64   `json:"CheckAndPut_90th_percentile,omitempty"`
	CheckAndPut95ThPercentile                     *int64   `json:"CheckAndPut_95th_percentile,omitempty"`
	CheckAndPut98ThPercentile                     *int64   `json:"CheckAndPut_98th_percentile,omitempty"`
	CheckAndPut99ThPercentile                     *int64   `json:"CheckAndPut_99th_percentile,omitempty"`
	CheckAndPut999ThPercentile                    *int64   `json:"CheckAndPut_99.9th_percentile,omitempty"`
	SplitTimeNumOps                               *int64   `json:"SplitTime_num_ops,omitempty"`
	SplitTimeMin                                  *int64   `json:"SplitTime_min,omitempty"`
	SplitTimeMax                                  *int64   `json:"SplitTime_max,omitempty"`
	SplitTimeMean                                 *int64   `json:"SplitTime_mean,omitempty"`
	SplitTime25ThPercentile                       *int64   `json:"SplitTime_25th_percentile,omitempty"`
	SplitTimeMedian                               *int64   `json:"SplitTime_median,omitempty"`
	SplitTime75ThPercentile                       *int64   `json:"SplitTime_75th_percentile,omitempty"`
	SplitTime90ThPercentile                       *int64   `json:"SplitTime_90th_percentile,omitempty"`
	SplitTime95ThPercentile                       *int64   `json:"SplitTime_95th_percentile,omitempty"`
	SplitTime98ThPercentile                       *int64   `json:"SplitTime_98th_percentile,omitempty"`
	SplitTime99ThPercentile                       *int64   `json:"SplitTime_99th_percentile,omitempty"`
	SplitTime999ThPercentile                      *int64   `json:"SplitTime_99.9th_percentile,omitempty"`
	MajorCompactionOutputSizeNumOps               *int64   `json:"MajorCompactionOutputSize_num_ops,omitempty"`
	MajorCompactionOutputSizeMin                  *int64   `json:"MajorCompactionOutputSize_min,omitempty"`
	MajorCompactionOutputSizeMax                  *int64   `json:"MajorCompactionOutputSize_max,omitempty"`
	MajorCompactionOutputSizeMean                 *int64   `json:"MajorCompactionOutputSize_mean,omitempty"`
	MajorCompactionOutputSize25ThPercentile       *int64   `json:"MajorCompactionOutputSize_25th_percentile,omitempty"`
	MajorCompactionOutputSizeMedian               *int64   `json:"MajorCompactionOutputSize_median,omitempty"`
	MajorCompactionOutputSize75ThPercentile       *int64   `json:"MajorCompactionOutputSize_75th_percentile,omitempty"`
	MajorCompactionOutputSize90ThPercentile       *int64   `json:"MajorCompactionOutputSize_90th_percentile,omitempty"`
	MajorCompactionOutputSize95ThPercentile       *int64   `json:"MajorCompactionOutputSize_95th_percentile,omitempty"`
	MajorCompactionOutputSize98ThPercentile       *int64   `json:"MajorCompactionOutputSize_98th_percentile,omitempty"`
	MajorCompactionOutputSize99ThPercentile       *int64   `json:"MajorCompactionOutputSize_99th_percentile,omitempty"`
	MajorCompactionOutputSize999ThPercentile      *int64   `json:"MajorCompactionOutputSize_99.9th_percentile,omitempty"`
	MajorCompactedInputBytes                      *int64   `json:"majorCompactedInputBytes,omitempty"`
	SlowAppendCount                               *int64   `json:"slowAppendCount,omitempty"`
	FlushedOutputBytes                            *int64   `json:"flushedOutputBytes,omitempty"`
	CompactionOutputFileCountNumOps               *int64   `json:"CompactionOutputFileCount_num_ops,omitempty"`
	CompactionOutputFileCountMin                  *int64   `json:"CompactionOutputFileCount_min,omitempty"`
	CompactionOutputFileCountMax                  *int64   `json:"CompactionOutputFileCount_max,omitempty"`
	CompactionOutputFileCountMean                 *int64   `json:"CompactionOutputFileCount_mean,omitempty"`
	CompactionOutputFileCount25ThPercentile       *int64   `json:"CompactionOutputFileCount_25th_percentile,omitempty"`
	CompactionOutputFileCountMedian               *int64   `json:"CompactionOutputFileCount_median,omitempty"`
	CompactionOutputFileCount75ThPercentile       *int64   `json:"CompactionOutputFileCount_75th_percentile,omitempty"`
	CompactionOutputFileCount90ThPercentile       *int64   `json:"CompactionOutputFileCount_90th_percentile,omitempty"`
	CompactionOutputFileCount95ThPercentile       *int64   `json:"CompactionOutputFileCount_95th_percentile,omitempty"`
	CompactionOutputFileCount98ThPercentile       *int64   `json:"CompactionOutputFileCount_98th_percentile,omitempty"`
	CompactionOutputFileCount99ThPercentile       *int64   `json:"CompactionOutputFileCount_99th_percentile,omitempty"`
	CompactionOutputFileCount999ThPercentile      *int64   `json:"CompactionOutputFileCount_99.9th_percentile,omitempty"`
	SlowDeleteCount                               *int64   `json:"slowDeleteCount,omitempty"`
	ReplayNumOps                                  *int64   `json:"Replay_num_ops,omitempty"`
	ReplayMin                                     *int64   `json:"Replay_min,omitempty"`
	ReplayMax                                     *int64   `json:"Replay_max,omitempty"`
	ReplayMean                                    *int64   `json:"Replay_mean,omitempty"`
	Replay25ThPercentile                          *int64   `json:"Replay_25th_percentile,omitempty"`
	ReplayMedian                                  *int64   `json:"Replay_median,omitempty"`
	Replay75ThPercentile                          *int64   `json:"Replay_75th_percentile,omitempty"`
	Replay90ThPercentile                          *int64   `json:"Replay_90th_percentile,omitempty"`
	Replay95ThPercentile                          *int64   `json:"Replay_95th_percentile,omitempty"`
	Replay98ThPercentile                          *int64   `json:"Replay_98th_percentile,omitempty"`
	Replay99ThPercentile                          *int64   `json:"Replay_99th_percentile,omitempty"`
	Replay999ThPercentile                         *int64   `json:"Replay_99.9th_percentile,omitempty"`
	FlushTimeNumOps                               *int64   `json:"FlushTime_num_ops,omitempty"`
	FlushTimeMin                                  *int64   `json:"FlushTime_min,omitempty"`
	FlushTimeMax                                  *int64   `json:"FlushTime_max,omitempty"`
	FlushTimeMean                                 *int64   `json:"FlushTime_mean,omitempty"`
	FlushTime25ThPercentile                       *int64   `json:"FlushTime_25th_percentile,omitempty"`
	FlushTimeMedian                               *int64   `json:"FlushTime_median,omitempty"`
	FlushTime75ThPercentile                       *int64   `json:"FlushTime_75th_percentile,omitempty"`
	FlushTime90ThPercentile                       *int64   `json:"FlushTime_90th_percentile,omitempty"`
	FlushTime95ThPercentile                       *int64   `json:"FlushTime_95th_percentile,omitempty"`
	FlushTime98ThPercentile                       *int64   `json:"FlushTime_98th_percentile,omitempty"`
	FlushTime99ThPercentile                       *int64   `json:"FlushTime_99th_percentile,omitempty"`
	FlushTime999ThPercentile                      *int64   `json:"FlushTime_99.9th_percentile,omitempty"`
	MajorCompactionInputSizeNumOps                *int64   `json:"MajorCompactionInputSize_num_ops,omitempty"`
	MajorCompactionInputSizeMin                   *int64   `json:"MajorCompactionInputSize_min,omitempty"`
	MajorCompactionInputSizeMax                   *int64   `json:"MajorCompactionInputSize_max,omitempty"`
	MajorCompactionInputSizeMean                  *int64   `json:"MajorCompactionInputSize_mean,omitempty"`
	MajorCompactionInputSize25ThPercentile        *int64   `json:"MajorCompactionInputSize_25th_percentile,omitempty"`
	MajorCompactionInputSizeMedian                *int64   `json:"MajorCompactionInputSize_median,omitempty"`
	MajorCompactionInputSize75ThPercentile        *int64   `json:"MajorCompactionInputSize_75th_percentile,omitempty"`
	MajorCompactionInputSize90ThPercentile        *int64   `json:"MajorCompactionInputSize_90th_percentile,omitempty"`
	MajorCompactionInputSize95ThPercentile        *int64   `json:"MajorCompactionInputSize_95th_percentile,omitempty"`
	MajorCompactionInputSize98ThPercentile        *int64   `json:"MajorCompactionInputSize_98th_percentile,omitempty"`
	MajorCompactionInputSize99ThPercentile        *int64   `json:"MajorCompactionInputSize_99th_percentile,omitempty"`
	MajorCompactionInputSize999ThPercentile       *int64   `json:"MajorCompactionInputSize_99.9th_percentile,omitempty"`
	PauseInfoThresholdExceeded                    *int64   `json:"pauseInfoThresholdExceeded,omitempty"`
	SplitSuccessCount                             *int64   `json:"splitSuccessCount,omitempty"`
	CheckAndDeleteNumOps                          *int64   `json:"CheckAndDelete_num_ops,omitempty"`
	CheckAndDeleteMin                             *int64   `json:"CheckAndDelete_min,omitempty"`
	CheckAndDeleteMax                             *int64   `json:"CheckAndDelete_max,omitempty"`
	CheckAndDeleteMean                            *int64   `json:"CheckAndDelete_mean,omitempty"`
	CheckAndDelete25ThPercentile                  *int64   `json:"CheckAndDelete_25th_percentile,omitempty"`
	CheckAndDeleteMedian                          *int64   `json:"CheckAndDelete_median,omitempty"`
	CheckAndDelete75ThPercentile                  *int64   `json:"CheckAndDelete_75th_percentile,omitempty"`
	CheckAndDelete90ThPercentile                  *int64   `json:"CheckAndDelete_90th_percentile,omitempty"`
	CheckAndDelete95ThPercentile                  *int64   `json:"CheckAndDelete_95th_percentile,omitempty"`
	CheckAndDelete98ThPercentile                  *int64   `json:"CheckAndDelete_98th_percentile,omitempty"`
	CheckAndDelete99ThPercentile                  *int64   `json:"CheckAndDelete_99th_percentile,omitempty"`
	CheckAndDelete999ThPercentile                 *int64   `json:"CheckAndDelete_99.9th_percentile,omitempty"`
	CompactionInputSizeNumOps                     *int64   `json:"CompactionInputSize_num_ops,omitempty"`
	CompactionInputSizeMin                        *int64   `json:"CompactionInputSize_min,omitempty"`
	CompactionInputSizeMax                        *int64   `json:"CompactionInputSize_max,omitempty"`
	CompactionInputSizeMean                       *int64   `json:"CompactionInputSize_mean,omitempty"`
	CompactionInputSize25ThPercentile             *int64   `json:"CompactionInputSize_25th_percentile,omitempty"`
	CompactionInputSizeMedian                     *int64   `json:"CompactionInputSize_median,omitempty"`
	CompactionInputSize75ThPercentile             *int64   `json:"CompactionInputSize_75th_percentile,omitempty"`
	CompactionInputSize90ThPercentile             *int64   `json:"CompactionInputSize_90th_percentile,omitempty"`
	CompactionInputSize95ThPercentile             *int64   `json:"CompactionInputSize_95th_percentile,omitempty"`
	CompactionInputSize98ThPercentile             *int64   `json:"CompactionInputSize_98th_percentile,omitempty"`
	CompactionInputSize99ThPercentile             *int64   `json:"CompactionInputSize_99th_percentile,omitempty"`
	CompactionInputSize999ThPercentile            *int64   `json:"CompactionInputSize_99.9th_percentile,omitempty"`
	MajorCompactionOutputFileCountNumOps          *int64   `json:"MajorCompactionOutputFileCount_num_ops,omitempty"`
	MajorCompactionOutputFileCountMin             *int64   `json:"MajorCompactionOutputFileCount_min,omitempty"`
	MajorCompactionOutputFileCountMax             *int64   `json:"MajorCompactionOutputFileCount_max,omitempty"`
	MajorCompactionOutputFileCountMean            *int64   `json:"MajorCompactionOutputFileCount_mean,omitempty"`
	MajorCompactionOutputFileCount25ThPercentile  *int64   `json:"MajorCompactionOutputFileCount_25th_percentile,omitempty"`
	MajorCompactionOutputFileCountMedian          *int64   `json:"MajorCompactionOutputFileCount_median,omitempty"`
	MajorCompactionOutputFileCount75ThPercentile  *int64   `json:"MajorCompactionOutputFileCount_75th_percentile,omitempty"`
	MajorCompactionOutputFileCount90ThPercentile  *int64   `json:"MajorCompactionOutputFileCount_90th_percentile,omitempty"`
	MajorCompactionOutputFileCount95ThPercentile  *int64   `json:"MajorCompactionOutputFileCount_95th_percentile,omitempty"`
	MajorCompactionOutputFileCount98ThPercentile  *int64   `json:"MajorCompactionOutputFileCount_98th_percentile,omitempty"`
	MajorCompactionOutputFileCount99ThPercentile  *int64   `json:"MajorCompactionOutputFileCount_99th_percentile,omitempty"`
	MajorCompactionOutputFileCount999ThPercentile *int64   `json:"MajorCompactionOutputFileCount_99.9th_percentile,omitempty"`
	ScanSizeNumOps                                *int64   `json:"ScanSize_num_ops,omitempty"`
	ScanSizeMin                                   *int64   `json:"ScanSize_min,omitempty"`
	ScanSizeMax                                   *int64   `json:"ScanSize_max,omitempty"`
	ScanSizeMean                                  *int64   `json:"ScanSize_mean,omitempty"`
	ScanSize25ThPercentile                        *int64   `json:"ScanSize_25th_percentile,omitempty"`
	ScanSizeMedian                                *int64   `json:"ScanSize_median,omitempty"`
	ScanSize75ThPercentile                        *int64   `json:"ScanSize_75th_percentile,omitempty"`
	ScanSize90ThPercentile                        *int64   `json:"ScanSize_90th_percentile,omitempty"`
	ScanSize95ThPercentile                        *int64   `json:"ScanSize_95th_percentile,omitempty"`
	ScanSize98ThPercentile                        *int64   `json:"ScanSize_98th_percentile,omitempty"`
	ScanSize99ThPercentile                        *int64   `json:"ScanSize_99th_percentile,omitempty"`
	ScanSize999ThPercentile                       *int64   `json:"ScanSize_99.9th_percentile,omitempty"`
	SlowGetCount                                  *int64   `json:"slowGetCount,omitempty"`
	FlushedMemstoreBytes                          *int64   `json:"flushedMemstoreBytes,omitempty"`
	CompactionOutputSizeNumOps                    *int64   `json:"CompactionOutputSize_num_ops,omitempty"`
	CompactionOutputSizeMin                       *int64   `json:"CompactionOutputSize_min,omitempty"`
	CompactionOutputSizeMax                       *int64   `json:"CompactionOutputSize_max,omitempty"`
	CompactionOutputSizeMean                      *int64   `json:"CompactionOutputSize_mean,omitempty"`
	CompactionOutputSize25ThPercentile            *int64   `json:"CompactionOutputSize_25th_percentile,omitempty"`
	CompactionOutputSizeMedian                    *int64   `json:"CompactionOutputSize_median,omitempty"`
	CompactionOutputSize75ThPercentile            *int64   `json:"CompactionOutputSize_75th_percentile,omitempty"`
	CompactionOutputSize90ThPercentile            *int64   `json:"CompactionOutputSize_90th_percentile,omitempty"`
	CompactionOutputSize95ThPercentile            *int64   `json:"CompactionOutputSize_95th_percentile,omitempty"`
	CompactionOutputSize98ThPercentile            *int64   `json:"CompactionOutputSize_98th_percentile,omitempty"`
	CompactionOutputSize99ThPercentile            *int64   `json:"CompactionOutputSize_99th_percentile,omitempty"`
	CompactionOutputSize999ThPercentile           *int64   `json:"CompactionOutputSize_99.9th_percentile,omitempty"`
	MajorCompactedOutputBytes                     *int64   `json:"majorCompactedOutputBytes,omitempty"`
	PauseTimeWithoutGcNumOps                      *int64   `json:"PauseTimeWithoutGc_num_ops,omitempty"`
	PauseTimeWithoutGcMin                         *int64   `json:"PauseTimeWithoutGc_min,omitempty"`
	PauseTimeWithoutGcMax                         *int64   `json:"PauseTimeWithoutGc_max,omitempty"`
	PauseTimeWithoutGcMean                        *int64   `json:"PauseTimeWithoutGc_mean,omitempty"`
	PauseTimeWithoutGc25ThPercentile              *int64   `json:"PauseTimeWithoutGc_25th_percentile,omitempty"`
	PauseTimeWithoutGcMedian                      *int64   `json:"PauseTimeWithoutGc_median,omitempty"`
	PauseTimeWithoutGc75ThPercentile              *int64   `json:"PauseTimeWithoutGc_75th_percentile,omitempty"`
	PauseTimeWithoutGc90ThPercentile              *int64   `json:"PauseTimeWithoutGc_90th_percentile,omitempty"`
	PauseTimeWithoutGc95ThPercentile              *int64   `json:"PauseTimeWithoutGc_95th_percentile,omitempty"`
	PauseTimeWithoutGc98ThPercentile              *int64   `json:"PauseTimeWithoutGc_98th_percentile,omitempty"`
	PauseTimeWithoutGc99ThPercentile              *int64   `json:"PauseTimeWithoutGc_99th_percentile,omitempty"`
	PauseTimeWithoutGc999ThPercentile             *int64   `json:"PauseTimeWithoutGc_99.9th_percentile,omitempty"`
	SlowPutCount                                  *int64   `json:"slowPutCount,omitempty"`
	SlowIncrementCount                            *int64   `json:"slowIncrementCount,omitempty"`
	CompactedInputBytes                           *int64   `json:"compactedInputBytes,omitempty"`
	AppendNumOps                                  *int64   `json:"Append_num_ops,omitempty"`
	AppendMin                                     *int64   `json:"Append_min,omitempty"`
	AppendMax                                     *int64   `json:"Append_max,omitempty"`
	AppendMean                                    *int64   `json:"Append_mean,omitempty"`
	Append25ThPercentile                          *int64   `json:"Append_25th_percentile,omitempty"`
	AppendMedian                                  *int64   `json:"Append_median,omitempty"`
	Append75ThPercentile                          *int64   `json:"Append_75th_percentile,omitempty"`
	Append90ThPercentile                          *int64   `json:"Append_90th_percentile,omitempty"`
	Append95ThPercentile                          *int64   `json:"Append_95th_percentile,omitempty"`
	Append98ThPercentile                          *int64   `json:"Append_98th_percentile,omitempty"`
	Append99ThPercentile                          *int64   `json:"Append_99th_percentile,omitempty"`
	Append999ThPercentile                         *int64   `json:"Append_99.9th_percentile,omitempty"`
	FlushOutputSizeNumOps                         *int64   `json:"FlushOutputSize_num_ops,omitempty"`
	FlushOutputSizeMin                            *int64   `json:"FlushOutputSize_min,omitempty"`
	FlushOutputSizeMax                            *int64   `json:"FlushOutputSize_max,omitempty"`
	FlushOutputSizeMean                           *int64   `json:"FlushOutputSize_mean,omitempty"`
	FlushOutputSize25ThPercentile                 *int64   `json:"FlushOutputSize_25th_percentile,omitempty"`
	FlushOutputSizeMedian                         *int64   `json:"FlushOutputSize_median,omitempty"`
	FlushOutputSize75ThPercentile                 *int64   `json:"FlushOutputSize_75th_percentile,omitempty"`
	FlushOutputSize90ThPercentile                 *int64   `json:"FlushOutputSize_90th_percentile,omitempty"`
	FlushOutputSize95ThPercentile                 *int64   `json:"FlushOutputSize_95th_percentile,omitempty"`
	FlushOutputSize98ThPercentile                 *int64   `json:"FlushOutputSize_98th_percentile,omitempty"`
	FlushOutputSize99ThPercentile                 *int64   `json:"FlushOutputSize_99th_percentile,omitempty"`
	FlushOutputSize999ThPercentile                *int64   `json:"FlushOutputSize_99.9th_percentile,omitempty"`
	BulkloadCount                                 *int64   `json:"Bulkload_count,omitempty"`
	BulkloadMeanRate                              *int64   `json:"Bulkload_mean_rate,omitempty"`
	Bulkload1MinRate                              *int64   `json:"Bulkload_1min_rate,omitempty"`
	Bulkload5MinRate                              *int64   `json:"Bulkload_5min_rate,omitempty"`
	Bulkload15MinRate                             *int64   `json:"Bulkload_15min_rate,omitempty"`
	BulkloadNumOps                                *int64   `json:"Bulkload_num_ops,omitempty"`
	BulkloadMin                                   *int64   `json:"Bulkload_min,omitempty"`
	BulkloadMax                                   *int64   `json:"Bulkload_max,omitempty"`
	BulkloadMean                                  *int64   `json:"Bulkload_mean,omitempty"`
	Bulkload25ThPercentile                        *int64   `json:"Bulkload_25th_percentile,omitempty"`
	BulkloadMedian                                *int64   `json:"Bulkload_median,omitempty"`
	Bulkload75ThPercentile                        *int64   `json:"Bulkload_75th_percentile,omitempty"`
	Bulkload90ThPercentile                        *int64   `json:"Bulkload_90th_percentile,omitempty"`
	Bulkload95ThPercentile                        *int64   `json:"Bulkload_95th_percentile,omitempty"`
	Bulkload98ThPercentile                        *int64   `json:"Bulkload_98th_percentile,omitempty"`
	Bulkload99ThPercentile                        *int64   `json:"Bulkload_99th_percentile,omitempty"`
	Bulkload999ThPercentile                       *int64   `json:"Bulkload_99.9th_percentile,omitempty"`
	ServerReadQueryPerSecondCount                 *int64   `json:"ServerReadQueryPerSecond_count,omitempty"`
	ServerReadQueryPerSecondMeanRate              *int64   `json:"ServerReadQueryPerSecond_mean_rate,omitempty"`
	ServerReadQueryPerSecond1MinRate              *int64   `json:"ServerReadQueryPerSecond_1min_rate,omitempty"`
	ServerReadQueryPerSecond5MinRate              *int64   `json:"ServerReadQueryPerSecond_5min_rate,omitempty"`
	ServerReadQueryPerSecond15MinRate             *int64   `json:"ServerReadQueryPerSecond_15min_rate,omitempty"`
	ServerWriteQueryPerSecondCount                *int64   `json:"ServerWriteQueryPerSecond_count,omitempty"`
	ServerWriteQueryPerSecondMeanRate             *int64   `json:"ServerWriteQueryPerSecond_mean_rate,omitempty"`
	ServerWriteQueryPerSecond1MinRate             *int64   `json:"ServerWriteQueryPerSecond_1min_rate,omitempty"`
	ServerWriteQueryPerSecond5MinRate             *int64   `json:"ServerWriteQueryPerSecond_5min_rate,omitempty"`
	ServerWriteQueryPerSecond15MinRate            *int64   `json:"ServerWriteQueryPerSecond_15min_rate,omitempty"`
}
